### ISSUE TITLE
missing pretrain weight

### ISSUE THREAD

**Issue by TsinghuaPhantom** [rohitgajawada/Where-are-they-looking-PyTorch#2]
I cannot find the pretrain weight file whole_alexnet_places365.pth.tar.

**Comment by TsinghuaPhantom** [comment]
Problem Solved.
https://github.com/CSAILVision/places365

**Comment by rohitgajawada** [comment]
you can download it from here also if you want: https://drive.google.com/file/d/13h7bYEht2poZ7vD_HgzA7ggSPi0cmSBg/view?usp=sharing
