### ISSUE TITLE
a file can not be found

### ISSUE THREAD

**Issue by nanzhixionggit** [rohitgajawada/Where-are-they-looking-PyTorch#3]
in the gazenet.py, there is a class named alexsal that need a file named whole_alexnet_places365.pth.tar.
However, the file is not found

**Comment by rohitgajawada** [comment]
Hi, please download it from here :)

https://drive.google.com/file/d/13h7bYEht2poZ7vD_HgzA7ggSPi0cmSBg/view?usp=sharing
