### ISSUE TITLE
Hello, is there any pretrained model? How about the best distance of error? Thank you for your reply! 

### ISSUE THREAD

**Issue by Junpliu** [rohitgajawada/Where-are-they-looking-PyTorch#5]
Hello, is there any pretrained model? How about the best distance of error? Thank you for your reply!

**Comment by rohitgajawada** [comment]
I can give you a pretrained model if you require. However, I'm only able to reach about 0.19 mindist error where in the paper it is 0.12, would this be okay for you? I mailed the author a few weeks ago asking for any extra training details as all the details seem to not be provided in the paper I think, I'm still waiting for a reply.
